# Base docker compose, added to by docker-compose.override or docker-compose.prod. See Readme.md

version: '3'

services:

  # PHP & apache container using offical Docker PHP iamge
  web:
    # If pre-built image from docker hub exists then use that (docker pull openenergymonitor/emoncms:latest) if not Buildcontainer see Dockerflile
    image: openenergymonitor/emoncms:latest
    restart: always
    build: .
    volumes:
      # mount docker volumes persistant inside docker container
      - emon-phpfina:/var/opt/emoncms/phpfina
      - emon-phptimeseries:/var/opt/emoncms/phptimeseries
      - emon-cms:/var/www/emoncms
    links:
      # Link to MYSQL DB (see below)
      - db
      - redis
    ports:
      - "88:80"
    env_file:
      - "./default.docker-env"
      - "./config/emoncms.env"

    working_dir: /var/www/emoncms

  # MYSQL Database
  db:
    # Official MYSQL docker image
    # To do: make compatiable with 5.7
    image: mariadb:10
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_HOST: localhost
    ports:
      - "3306"
    volumes:
      - emon-db-data:/var/lib/mysql
  redis:
    build: ./redis
    volumes:
      - emon-redis-data:/data
  mqtt:
    restart: unless-stopped
    build: ./mqtt
  mqtt_writer:
    restart: unless-stopped
    build: ./mqtt

volumes:
  emon-phpfiwa:
  emon-phpfina:
  emon-phptimeseries:
  emon-db-data:
  emon-redis-data:
  emon-cms: