# Base docker compose, added to by docker-compose.override or docker-compose.prod. See Readme.md

version: '2.1'

services:
  # PHP & apache container using offical Docker PHP iamge
  web:
    env_file:
      - ./default.docker-env
      - ./config/emoncms.env
    # If pre-built image from docker hub exists then use that (docker pull openenergymonitor/emoncms:latest) if not Buildcontainer see Dockerflile
    image: openenergymonitor/emoncms:latest
    build: .
    volumes:
      # mount docker volumes persistant inside docker container
      - emon-phpfina:/var/opt/emoncms/phpfina
      - emon-phptimeseries:/var/opt/emoncms/phptimeseries
      - emon-cms:/var/www/emoncms
    links:
      - db
      - redis
    working_dir: /var/www/emoncms
    command: ["/usr/sbin/apachectl", "-D", "FOREGROUND"]

  # MYSQL Database
  db:
    env_file:
      - ./default.docker-env
      - ./config/emoncms.env
    image: mariadb:latest
    # wait for mysql server to be up
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - emon-db-data:/var/lib/mysql
      - ./mysql:/etc/mysql/conf.d

  redis:
    env_file:
      - ./default.docker-env
      - ./config/emoncms.env
    build: ./redis
    volumes:
      - emon-redis-data:/data

  mqtt:
    env_file:
      - ./default.docker-env
      - ./config/emoncms.env
    build: ./mqtt

  emoncms_mqtt:
    image: openenergymonitor/emoncms:latest
    env_file:
      - ./default.docker-env
      - ./config/emoncms.env
    links:
      - db
      - redis
    command: ["/usr/local/bin/php", "/var/www/emoncms/scripts/services/emoncms_mqtt/emoncms_mqtt.php", "2>&1", ">", "/var/log/mqtt_input.log"]
    volumes:
      - emon-cms:/var/www/emoncms

  emoncms_feedwriter:
    image: openenergymonitor/emoncms:latest
    env_file:
        - ./default.docker-env
        - ./config/emoncms.env
    links:
        - db
        - redis
    command: ["/usr/local/bin/php", "/var/www/emoncms/scripts/feedwriter.php"]
    volumes:
        - emon-cms:/var/www/emoncms

  emoncms_service-runner:
    image: openenergymonitor/emoncms:latest
    env_file:
        - ./default.docker-env
        - ./config/emoncms.env
    links:
        - db
        - redis
    command: ["/usr/bin/python", "/var/www/emoncms/scripts/services/service-runner/service-runner.py"]
    volumes:
        - emon-cms:/var/www/emoncms
         
volumes:
  emon-phpfiwa:
  emon-phpfina:
  emon-phptimeseries:
  emon-db-data:
  emon-redis-data:
  emon-cms: