# dev enviroment setup

version: '2.1'
services:

  web:
    ports:
      # Expose Emoncms on localhost port 88
      - 88:80
    volumes:
      #mount emoncms files from local FS for dev
      - .:/var/www/emoncms
    environment:
      - LOG_LEVEL=2
    command: bash -c "/var/www/emoncms/scripts/log-to-stout.sh && /usr/sbin/apachectl -D FOREGROUND"
  
  emoncms_mqtt:
    volumes:
      - .:/var/www/emoncms
  emoncms_feedwriter:
    volumes:
      - .:/var/www/emoncms
  emoncms_service-runner:
    volumes:
      - .:/var/www/emoncms