version: "2.1"
services:
    web:
        ports:
            - 88:80
    db:
        ports:
            - 3307:3306
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=true
            - MYSQL_DATABASE=emoncms
            - MYSQL_PASSWORD=YOUR_SECURE_PASSWORD
            - MYSQL_USER=emoncms
    redis:
        ports:
            - 6378:6379
