FROM balenalib/%%BALENA_MACHINE_NAME%%-debian
RUN install_packages \
   libcurl4-gnutls-dev \
   libmcrypt-dev \
   libmosquitto-dev \
   gettext \
   nano \
   git-core 

# # Enable PHP modules
RUN docker-php-ext-install -j$(nproc) mysqli curl json gettext
# RUN pecl install redis \
#   \ && docker-php-ext-enable redis
# RUN pecl install Mosquitto-beta \
#   \ && docker-php-ext-enable mosquitto
#
#
