FROM arm32v7/php:7.4-apache-buster
COPY . /usr/src/myapp
WORKDIR /usr/src/myapp
# CMD [ "php", "./index.php" ]
CMD ["php -S localhost:80"]
# RUN apt-get update
# RUN apt-get update && apt-get install -y \
            #   libcurl4-gnutls-dev \
            #   libmcrypt-dev \
            #   libmosquitto-dev \
            #   gettext \
            #   nano \
            #   git-core 


# # Enable PHP modules
# RUN docker-php-ext-install -j$(nproc) mysqli curl json gettext
# RUN pecl install redis \
#   \ && docker-php-ext-enable redis
# RUN pecl install Mosquitto-beta \
#   \ && docker-php-ext-enable mosquitto