FROM arm32v7/php:7.4-apache-buster
# FROM arm32v7/php:7.4-apache-buster
COPY . /var/www/html
WORKDIR /var/www/html

RUN install_packages libcurl4-gnutls-dev

# RUN apt-get update && apt-get install -y \
            #   libcurl4-gnutls-dev \
            #   libmcrypt-dev \
            #   libmosquitto-dev \
            #   gettext \
            #   nano \
            #   git-core 


# # Enable PHP modules
# RUN docker-php-ext-install -j$(nproc) mysqli curl json gettext
# RUN pecl install redis \
#   \ && docker-php-ext-enable redis
# RUN pecl install Mosquitto-beta \
#   \ && docker-php-ext-enable mosquitto
