version: "2.1"
services:
   web:
        build: .
        ports:
                - "89:80"
        volumes:
                - code:/code
        links:
                - php
   php:
        image: php:7-fpm
        volumes:
                - code:/code
volumes:
        code:
