FROM balenalib/%%BALENA_MACHINE_NAME%%-debian:stretch-run
COPY qemu/arm-linux-user/qemu-arm /usr/bin

# APACHE, MYSQL, GETTEXT, GIT
RUN apt-get update -qq && apt-get install -y --no-install-recommends \
    apache2 \
    libapache2-mod-php \
    libcurl4-gnutls-dev \
    libmcrypt-dev \
    libmosquitto-dev \
    gettext \
    nano \
    git-core 

# Install PHP
RUN apt-get install -y --no-install-recommends \
    php \
    php-pear \
    php-common \
    php-mysqli \
    php-curl \
    php-cli \
    php-dev \
    php-imap \
    php-mbstring \
    php-zip 

# Enable PHP modules
RUN pecl install redis Mosquitto-beta mcrypt-1.0.2
RUN phpenmod redis mosquitto mcrypt

# Enable apache modules
RUN a2enmod rewrite

# Add custom PHP config
COPY config/php.ini /usr/local/etc/php/

# EmonCMS Code
RUN mkdir /var/www/emoncms
RUN git clone https://github.com/emoncms/emoncms.git /var/www/emoncms
RUN git clone https://github.com/emoncms/device.git /var/www/emoncms/Modules/device

# Add custom Apache config, disable default and enable emoncms
COPY config/emoncms.conf /etc/apache2/sites-available/
RUN a2dissite 000-default.conf
RUN a2ensite emoncms

# Empty directories to save space
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Log files
RUN touch /var/log/emoncms/emoncms.log
RUN chmod 666 /var/log/emoncms/emoncms.log

# Starting Directory
WORKDIR /var/www/emoncms


