
#FROM balenalib/raspberrypi3-debian:stretch-run
#COPY ./qemu/arm-linux-user/qemu-arm /usr/bin/qemu-arm-static
#RUN /usr/bin/qemu-arm-static /bin/sh -c /bin/echo Hello from ARM container


FROM arm32v7/debian:stretch-slim
 
# COPY qemu/arm-linux-user/qemu-arm /usr/bin
 
RUN apt-get update;\
    apt-get install -y nginx;\
    echo "\ndaemon off;" >> /etc/nginx/nginx.conf
 
CMD ["nginx"]
