version: "2.1"
services:
    web:
        env_file:
             - ../../default.docker-env
             - config/emoncms.env
        image: emoncms
        build: .
        volumes:
             - emon-phpfina:/var/opt/emoncms/phpfina/
             - emon-phptimeseries:/var/opt/emoncms/phptimeseries/
             - emon-log:/var/log/emoncms/
             - emon-cms:/var/www/emoncms/
        ports:
             - 88:80
        environment:
             - LOG_LEVEL=1
             - MQTT_ENABLED=true
             - MQTT_HOST=mqtt
             - REDIS_ENABLED=false
        command: ["/usr/sbin/apache2ctl","-D","FOREGROUND"]

volumes:
    emon-phpfina:
    emon-phptimeseries:
    emon-log:
    emon-cms:   
